# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mod1_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ctypes.wintypes import RGB
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage, QColor, QPixelFormat
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QAction, QMainWindow, QSlider, QPushButton, QToolTip, QApplication
from PIL import Image, ImageOps, ImageEnhance, ImageColor
from PIL.ImageQt import ImageQt
import cv2
import numpy as np


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 421)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 551, 391))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btnRed = QtWidgets.QRadioButton(self.tab)
        self.btnRed.setGeometry(QtCore.QRect(470, 60, 80, 18))
        self.btnRed.setObjectName("btnRed")
        self.btnGreen = QtWidgets.QRadioButton(self.tab)
        self.btnGreen.setGeometry(QtCore.QRect(470, 90, 80, 18))
        self.btnGreen.setObjectName("btnGreen")
        self.btnBlue = QtWidgets.QRadioButton(self.tab)
        self.btnBlue.setGeometry(QtCore.QRect(470, 120, 80, 18))
        self.btnBlue.setObjectName("btnBlue")
        self.btnCyn = QtWidgets.QRadioButton(self.tab)
        self.btnCyn.setGeometry(QtCore.QRect(470, 240, 80, 18))
        self.btnCyn.setObjectName("btnCyn")
        self.btnMagenta = QtWidgets.QRadioButton(self.tab)
        self.btnMagenta.setGeometry(QtCore.QRect(470, 270, 80, 18))
        self.btnMagenta.setObjectName("btnMagenta")
        self.btnYellow = QtWidgets.QRadioButton(self.tab)
        self.btnYellow.setGeometry(QtCore.QRect(470, 300, 80, 18))
        self.btnYellow.setObjectName("btnYellow")
        self.openButton = QtWidgets.QPushButton(self.tab)
        self.openButton.setGeometry(QtCore.QRect(10, 260, 75, 23))
        self.openButton.setObjectName("openButton")
        self.copyButton = QtWidgets.QPushButton(self.tab)
        self.copyButton.setGeometry(QtCore.QRect(130, 260, 75, 23))
        self.copyButton.setObjectName("copyButton")
        self.exitButton = QtWidgets.QPushButton(self.tab)
        self.exitButton.setGeometry(QtCore.QRect(70, 300, 75, 23))
        self.exitButton.setObjectName("exitButton")
        self.pictureBox = QtWidgets.QLabel(self.tab)
        self.pictureBox.setGeometry(QtCore.QRect(10, 80, 191, 151))
        self.pictureBox.setAutoFillBackground(False)
        self.pictureBox.setFrameShape(QtWidgets.QFrame.Panel)
        self.pictureBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pictureBox.setText("")
        self.pictureBox.setScaledContents(True)
        self.pictureBox.setObjectName("pictureBox")
        self.pictureBox2 = QtWidgets.QLabel(self.tab)
        self.pictureBox2.setGeometry(QtCore.QRect(240, 20, 191, 151))
        self.pictureBox2.setAutoFillBackground(False)
        self.pictureBox2.setFrameShape(QtWidgets.QFrame.Panel)
        self.pictureBox2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pictureBox2.setText("")
        self.pictureBox2.setScaledContents(True)
        self.pictureBox2.setObjectName("pictureBox2")
        self.pictureBox3 = QtWidgets.QLabel(self.tab)
        self.pictureBox3.setGeometry(QtCore.QRect(240, 200, 191, 151))
        self.pictureBox3.setAutoFillBackground(False)
        self.pictureBox3.setFrameShape(QtWidgets.QFrame.Panel)
        self.pictureBox3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pictureBox3.setText("")
        self.pictureBox3.setScaledContents(True)
        self.pictureBox3.setObjectName("pictureBox3")
        self.labelCitraAsli = QtWidgets.QLabel(self.tab)
        self.labelCitraAsli.setGeometry(QtCore.QRect(80, 60, 47, 14))
        self.labelCitraAsli.setFrameShape(QtWidgets.QFrame.Box)
        self.labelCitraAsli.setObjectName("labelCitraAsli")
        self.labelCitraRGB = QtWidgets.QLabel(self.tab)
        self.labelCitraRGB.setGeometry(QtCore.QRect(310, 0, 51, 16))
        self.labelCitraRGB.setFrameShape(QtWidgets.QFrame.Box)
        self.labelCitraRGB.setObjectName("labelCitraRGB")
        self.labelCitraCMY = QtWidgets.QLabel(self.tab)
        self.labelCitraCMY.setGeometry(QtCore.QRect(309, 180, 51, 16))
        self.labelCitraCMY.setFrameShape(QtWidgets.QFrame.Box)
        self.labelCitraCMY.setObjectName("labelCitraCMY")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 22))
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName("menubar")
        self.menuModul1 = QtWidgets.QMenu(self.menubar)
        self.menuModul1.setObjectName("menuModul1")
        self.menuModul2 = QtWidgets.QMenu(self.menubar)
        self.menuModul2.setObjectName("menuModul2")
        self.menuModul3 = QtWidgets.QMenu(self.menubar)
        self.menuModul3.setObjectName("menuModul3")
        self.menuModul4 = QtWidgets.QMenu(self.menubar)
        self.menuModul4.setObjectName("menuModul4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.menuModul1.addAction(self.actionNew)
        self.menuModul1.addSeparator()
        self.menubar.addAction(self.menuModul1.menuAction())
        self.menubar.addAction(self.menuModul2.menuAction())
        self.menubar.addAction(self.menuModul3.menuAction())
        self.menubar.addAction(self.menuModul4.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.openButton.clicked.connect(self.loadImage)
        self.copyButton.clicked.connect(self.copyImage)
        # self.exitButton.clicked.connect(lambda:self.close())
        self.btnRed.clicked.connect(self.convertRed)
        self.btnGreen.clicked.connect(self.convertGreen)
        self.btnBlue.clicked.connect(self.convertBlue)
        self.btnCyn.clicked.connect(self.convertCyan)
        self.btnMagenta.clicked.connect(self.convertMagenta)
        self.btnYellow.clicked.connect(self.convertYellow)
        self.exitButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PraktikumPengolahanCitraDigital"))
        self.btnRed.setText(_translate("MainWindow", "Red"))
        self.btnGreen.setText(_translate("MainWindow", "Green"))
        self.btnBlue.setText(_translate("MainWindow", "Blue"))
        self.btnCyn.setText(_translate("MainWindow", "Cyan"))
        self.btnMagenta.setText(_translate("MainWindow", "Magenta"))
        self.btnYellow.setText(_translate("MainWindow", "Yellow"))
        self.openButton.setText(_translate("MainWindow", "Open"))
        self.copyButton.setText(_translate("MainWindow", "Copy"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.labelCitraAsli.setText(_translate("MainWindow", "Citra Asli"))
        self.labelCitraRGB.setText(_translate("MainWindow", "Citra RGB"))
        self.labelCitraCMY.setText(_translate("MainWindow", "Citra CMY"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Modul 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Modul 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Modul 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Modul 4"))
        self.menubar.setStatusTip(_translate("MainWindow", "Modul1"))
        self.menuModul1.setTitle(_translate("MainWindow", "File"))
        self.menuModul2.setTitle(_translate("MainWindow", "Edit"))
        self.menuModul3.setTitle(_translate("MainWindow", "View"))
        self.menuModul4.setTitle(_translate("MainWindow", "Setting"))
        self.actionNew.setText(_translate("MainWindow", "New"))

    def loadImage(self):
        self.namaImg, typeimg= QFileDialog.getOpenFileName(self.centralwidget, "Open Image", "", "*.jpg;;*.bmp;;All Files(*)")
        jpg = QPixmap(self.namaImg)

        self.pictureBox.setPixmap(jpg)

    def copyImage(self):
        img = Image.open(self.namaImg)
        width, height= img.size

        for row in range(height):
            for col in range(width):
                img.getpixel((col,row))

        img.save("copyim.jpg")     
        jpg=QPixmap("copyim.jpg")
        self.pictureBox2.setPixmap(jpg)
        # self.pictureBox3.setPixmap(jpg)

    def convertRed(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED)
        print(img.shape)

        red_channel = img[:,:,2]
        red_img = np.zeros(img.shape)
        red_img[:,:,2] = red_channel

        cv2.imwrite("hasilConvert.jpg", red_img) 
        jpg=QPixmap("hasilConvert.jpg")
        self.pictureBox2.setPixmap(jpg)
        # img = Image.open(self.namaImg).convert("L")
        # red=  ImageOps.colorize(img, black ="red", white ="white")
        # gImage = ImageQt(red)
        # # width, height= img.size
        # # for row in range(height):
        # #     for col in range(width):
        # #          img.getpixel((col,row))
        # #         #  newColor = ImageColor.getrgb("red")
        # #          img.putpixel((col,row),(255,0,0))
                 
        # gImage.save("hasilConvert.jpg")     
        # jpg=QPixmap("hasilConvert.jpg")
        # self.pictureBox2.setPixmap(jpg)
        
    def convertGreen(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED)
        print(img.shape)
        #BGR, 0=blue, 1=Greed, 2=Blue
        green_channel = img[:,:,1]
        green_img = np.zeros(img.shape)
        green_img[:,:,1] = green_channel

        cv2.imwrite("hasilConvert.jpg", green_img) 
        jpg=QPixmap("hasilConvert.jpg")
        self.pictureBox2.setPixmap(jpg)

    def convertBlue(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED) 
        print(img.shape)
        blue_channel = img[:,:,0] 
        blue_img = np.zeros(img.shape)
        blue_img[:,:,0] = blue_channel 

        #save image
        cv2.imwrite("hasilConvert.jpg", blue_img) 
        jpg=QPixmap("hasilConvert.jpg")
        self.pictureBox2.setPixmap(jpg)
   
    def convertCyan(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED)
        print(img.shape)
        
        img[:,:,2] = np.zeros([img.shape[0], img.shape[1]])

        #save image
        cv2.imwrite("hasilConvert.jpg", img) 
        jpg=QPixmap("hasilConvert.jpg")
        self.pictureBox3.setPixmap(jpg)
    
    def convertMagenta(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED)
        print(img.shape)

        img[:,:,1] = np.zeros([img.shape[0], img.shape[1]])

        #save image
        cv2.imwrite("hasilConvert.jpg", img) 
        jpg=QPixmap("hasilConvert.jpg")
        self.pictureBox3.setPixmap(jpg)
    
    def convertYellow(self):
        img = cv2.imread(self.namaImg, cv2.IMREAD_UNCHANGED)
        print(img.shape)
        img[:,:,0] = np.zeros([img.shape[0], img.shape[1]])

        #save image
        cv2.imwrite("hasilConvert.jpg", img) 
        jpg=QPixmap("hasilConvert.jpg")
        self.pictureBox3.setPixmap(jpg)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
